[package]
name = "mtb_terrain_gen"
version = "0.3.5"
edition = "2021"

[dependencies]
bevy = { version = "0.10.1", features = ["dynamic_linking"] }
bevy_common_assets = {  version ="0.6.0", features = ["toml"]}
bevy_debug_grid = "0.1"
libm = "0.2.7"
serde = "1.0"
noise = "0.8.2"
rand="0.8.5"
grid = { version = "*", default-features = false }

[workspace]
resolver = "2"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
