[[planes]]
name = "Water"
active = false
loc = [500.0, 1.0, 500.0]
subdivisions= [0,0]
dims = [1000.0, 1000.0]
color = {Color = [0.4, 0.92, 0.964, 1.0]}
modifiers = []

[[planes]]
name = "Beach"
active = true
loc = [500.0, 0.0, 100.0]
subdivisions= [20,40]
dims = [1000.0, 500.0]
color = {Gradient = {low = [0.647, 0.34, 0.205, 1.0], high = [0.976, 0.89, 0.768, 1.0]}}

[[planes.modifiers]]
[planes.modifiers.Shape]
shapetypedata = {AABB = {x=1000.0, z=500.0}}
loc = [0.0, 0.0]
height = 100.0

[[planes.modifiers]]
[planes.modifiers.Noise]
noise = "RMSS"
seed = 0
scale = 0.0005
global = false
octaves = 1

# [[planes.modifiers]]
# [planes.modifiers.Shape]
# shapetypedata = {AABB = {x=1000.0, z=0.0}}
# loc = [0.0, 0.0]
# height = 20.0

# [[planes.modifiers]]
# [planes.modifiers.Shape]
# shapetypedata = {AABB = {x=1000.0, z=100.0}}
# loc = [0.0, 400.0]
# height = 0.0