[[planes]]
name= "Greenish Perlin plane with flat edge x"
active= true
loc= [500.0, 0.0, -100.0]
subdivisions= [20,20]
dims= [500.0, 500.0]
color= {Color= [1.0, 1.0, 0.5, 1.0]}
modifiers =  [
   {Noise= {noise= "Perlin", seed = 0, scale= 0.01, height_scale= 50.0, global=true}},
   {FlatEdge = {edge= "X", height=0.0, dist = 50.0}},
   {SmoothEdge = {buffer = 100.0, method = "Distance"}}
]   

[[planes]]
name= "Yellow Perlin plane with flat edge x"
active= true
loc= [1000.0, 0.0, -100.0]
subdivisions= [20,20]
dims= [500.0, 500.0]
color= {Color= [1.0, 0.7, 0.224, 1.0]}
modifiers =  [
   {Noise= {noise= "PerlinSurflet", seed = 0, scale= 0.01, height_scale= 50.0, global=true}},
   {FlatEdges = {height=0.0, dist = 50.0}},
   {SmoothEdge = {buffer = 100.0, method = "Distance"}}
]   

[[planes]]
name= "Stepping color example"
active= true
loc= [0.0, 0.0, 400.0]
subdivisions= [60,60]
dims= [500.0, 500.0]
color= {Steps= [{"h"= -35.0, clr= [0.1, 0.2, 0.9, 1.0]}, {h = 0.0, clr=[1.0, 1.0, 0.3, 1.0]}, {h =200.0, clr=[0.4, 0.5, 0.1, 1.0]}]}
modifiers =  [
   {Noise= {noise= "PerlinSurflet", seed = 0, scale= 0.01, height_scale= 50.0, global=true}},
   {FlatEdges = {height=0.0, dist = 50.0}},
   {SmoothEdge = {buffer = 100.0, method = "Distance"}}
]  

[[planes]]
name= "Gradient color example"
active= true
loc= [1000.0, 0.0, 400.0]
subdivisions= [60,60]
dims= [500.0, 500.0]
color = {Gradient = {low = [0.0, 0.0, 1.0, 1.0], high = [1.0, 0.0, 0.0, 1.0]}}
modifiers =  [
   {Noise= {noise= "Value", seed = 0, scale= 0.01, height_scale= 100.0, global=true}},
]   

[[planes]]
name= "Gradient Perlin plane with easing"
active= true
loc= [500.0, 0.0, 400.0]
subdivisions= [20,20]
dims= [500.0, 500.0]
color = {Gradient = {low = [0.1, 0.5, 0.5, 1.0], high = [0.9, 0.5, 0.5, 1.0]}}
modifiers =  [
   {Noise  = {noise= "Simplex", seed = 6, scale= 0.005, height_scale= 10.0, global=true}},
   {Easing = {easing ="SmoothStart", global=true}}
]   