[[planes]]
name = "Water"
active = false 
loc = [500.0, 1.0, 500.0]
subdivisions= [0,0]
dims = [1000.0, 1000.0]
color = {Color = [0.4, 0.92, 0.964, 1.0]}
modifiers = []

[[planes]]
name = "Land"
active = false
loc = [500.0, 20.0, 500.0]
subdivisions= [0,0]
dims = [800.0, 800.0]
color = {Color = [0.976, 0.89, 0.768, 1.0]}
modifiers = []

