[[planes]]
name = "Green plane 1"
active = true
loc = [500.0, 0.0, 0.0]
subdivisions= [0,0]
dims = [1000.0, 500.0]
color = {Color = [0.545, 0.733, 0.345, 1.0]}
modifiers = []

[[planes]]
name = "Green plane 2"
active = true
loc = [500.0, 0.0, 800.0]
subdivisions= [0,0]
dims = [1000.0, 500.0]
color = {Color = [0.545, 0.733, 0.345, 1.0]}
modifiers = []

[[planes]]
name = "Water"
active = true
loc = [500.0, -4.0, 400.0]
subdivisions= [0,0]
dims = [1000.0, 300.0]
color = {Color = [0.4, 0.92, 0.964, 1.0]}
modifiers = []

[[planes]]
 name = "River Bed"
 active = true
 loc = [500.0, 0.0, 400.0]
 subdivisions = [10,10]
 dims = [1000.0, 300.0]
 color = {Gradient = {low = [0.976, 0.89, 0.768, 1.0], high = [0.545, 0.733, 0.345, 1.0]}}
 modifiers = [
   # {TargetWanderNoise = {wander = "Wanderer", width = 120.0, height = -20.0, step = 50.0, max_steps = 5000, source = {Point = [-500.0, 0.0]}, target = {Point = [500.0, 0.0]}, seed = "NoSeed"}} 
    {TargetWanderNoise = {wander = {Emu=30.0}, width = 100.0, height = -20.0, step = 10.0, max_steps = 5000, source = {Point = [-500.0, 0.0]}, target = {Point = [500.0, 0.0]}, seed = "NoSeed", easing="SmoothEnd"}}
 ]