[[planes]]
name = "Green plane 1"
active = true
loc = [500.0, 0.0, -100.0]
subdivisions= [0,0]
dims = [1000.0, 500.0]
color = {Color = [0.545, 0.733, 0.345, 1.0]}
modifiers = []

[[planes]]
name = "Green plane 2"
active = true
loc = [500.0, 0.0, 900.0]
subdivisions= [0,0]
dims = [1000.0, 500.0]
color = {Color = [0.545, 0.733, 0.345, 1.0]}
modifiers = []

[[planes]]
name = "Water"
active = true
loc = [500.0, -15.0, 400.0]
subdivisions= [0,0]
dims = [1000.0, 400.0]
color = {Color = [0.4, 0.92, 0.964, 1.0]}
modifiers = []

[[planes]]
 name = "River Bed"
 active = true
 loc = [500.0, 0.0, 400.0]
 subdivisions = [30,30]
 dims = [1000.0, 400.0]
 color = {Gradient = {low = [0.976, 0.89, 0.768, 1.0], high = [0.545, 0.733, 0.345, 1.0]}}
 modifiers = [
    {TargetWanderNoise = {wander = "Emu90", width = 170.0, height = -20.0, step = 10.0, max_steps = 5000, source = {Edge = "NX"}, target = {Edge = "X"}, seed = "NoSeed"}}, 
    {SmoothEdge = {buffer = 0.0, method = {"Value" = -5.0}}}
 ]