[[planes]]
name = "Water"
active = false
loc = [0.0, 60.0, 0.0]
subdivisions= [0,0]
dims = [1000.0, 1000.0]
color = {Color = [0.4, 0.92, 0.964, 1.0]}
modifiers = []


[[planes]]
name= "Test noise with easing"
active= true
loc= [0.0, 0.0, 0.0]
subdivisions= [40,40]
dims= [500.0, 500.0]
color = {Gradient = {low = [1.0, 0.0, 0.0, 1.0], high = [0.0, 1.0, 0.0, 1.0]}}

[[planes.modifiers]]
[planes.modifiers.Shape]
shapetypedata = {AABB = {x=1000.0, z=1000.0}}
loc = [0.0, 0.0]
val = {Value=50.0}

[[planes.modifiers]]
[planes.modifiers.Shape]
shapetypedata = {Ellipse = {x=100.0, z=200.0}}
loc = [120.0, 0.0]
val = {Value=-25.0}

[[planes.modifiers]]
[planes.modifiers.Noise]
noise = "FBMValue"
seed = 14
scale = 0.0045
global = false
easing = "None"
octaves = 6
freq = 2.0

# `Perlin`, `PerlinSurflet`, `OpenSimplex`, `Value`, `SuperSimplex`, `Worley`, 
# `Simplex`, `FBMPerlin`, `BMPerlin`, `BPerlin`, `RMPerlin`, `HMPerlin`, `FBMPerlinSurflet`, 
# `BMPerlinSurflet`, `BPerlinSurflet`, `RMPerlinSurflet`, `HMPerlinSurflet`, `FBMValue`, 
# `BMValue`, `BValue`, `RMValue`, `HMValue`, `FBMSS`, `BMSS`, `BSS`, `RMSS`, `HMSS`



# [[planes.modifiers]]
# [planes.modifiers.Shape]
# shapetypedata = {AABB = {x=100.0, z=500.0}}
# loc = [200.0, 0.0]
# val = {Value=50.0}

# [[planes.modifiers]]
# [planes.modifiers.Shape]
# shapetypedata = {AABB = {x=100.0, z=500.0}}
# loc = [200.0, 0.0]
# val = {Value=50.0}

# [[planes.modifiers]]
# [planes.modifiers.Shape]
# shapetypedata = {AABB = {x=300.0, z=500.0}}
# loc = [-100.0, 0.0]
# val = {Value=0.0}

# [[planes.modifiers]]
# [planes.modifiers.Terraces]
# terraces = [
#         [0.0, -10000.0, 0.0],
#         [10.0, 0.0, 10.0,],
#         [100.0, 10.0, 10000.0]]