[[planes]]
name = "Water"
active = false
loc = [0.0, 60.0, 0.0]
subdivisions= [0,0]
dims = [1000.0, 1000.0]
color = {Color = [0.4, 0.92, 0.964, 1.0]}
modifiers = []

[[planes]]
name= "Test noise with easing"
active= true
loc= [0.0, 0.0, 0.0]
subdivisions= [30,30]
dims= [500.0, 500.0]
color = {Gradient = {low = [1.0, 0.0, 0.0, 1.0], high = [0.0, 1.0, 0.0, 1.0]}}

[[planes.modifiers]]
[planes.modifiers.Value]
mb = {area = {AABB = {x=1000.0, z=1000.0}}, loc = [0.0, 0.0]}
scaling = "None"
easing = "None"
val = {Value=5.0}

[[planes.modifiers]]
[planes.modifiers.Value]
mb = {area = {Ellipse = {x=100.0, z=100.0}}, loc = [0.0, 0.0]}
# scaling = {DistanceCenter=0.5}
scaling = "None"
easing = "None"
val = {Diff=20.0}

[[planes.modifiers]]
[planes.modifiers.Value]
mb = {area = {Ellipse = {x=80.0, z=80.0}}, loc = [100.0, 0.0]}
# scaling = {DistanceCenter=0.5}
scaling = "None"
easing = "None"
val = {Diff=20.0}

[[planes.modifiers]]
[planes.modifiers.Value]
mb = {area = {Ellipse = {x=80.0, z=80.0}}, loc = [100.0, 67.0]}
# scaling = {DistanceCenter=0.5}
scaling = "None"
easing = "None"
val = {Diff=20.0}

[[planes.modifiers]]
[planes.modifiers.Value]
mb = {area = {Ellipse = {x=150.0, z=50.0}}, loc = [80.0,170.0]}
scaling = {DistanceCenter=0.5}
# scaling = "None"
easing = "None"
val = {Diff=20.0}

[[planes.modifiers]]
[planes.modifiers.Value]
mb = {area = {Ellipse = {x=150.0, z=50.0}}, loc = [-50.0,-60.0]}
# scaling = {DistanceCenter=0.5}
scaling = "None"
easing = "None"
val = {Value=20.0}

[[planes.modifiers]]
[planes.modifiers.Value]
mb = {area = {AABB = {x=150.0, z=200.0}}, loc = [-50.0,70.0]}
scaling = {DistanceCenter=0.1}
# scaling = "None"
easing = "SmoothStart"
val = {Value=20.0}

[[planes.modifiers]]
[planes.modifiers.Value]
mb = {area = {Ellipse = {x=60.0, z=120.0}}, loc = [-180.0, 70.0]}
# scaling = {DistanceCenter=0.1}
scaling = "None"
easing = "SmoothStart"
val = {Value=20.0}

[[planes.modifiers]]
[planes.modifiers.Value]
mb = {area = {Ellipse = {x=60.0, z=90.0}}, loc = [-120.0, 140.0]}
# scaling = {DistanceCenter=0.1}
scaling = "None"
easing = "SmoothStart"
val = {Diff=20.0}

[[planes.modifiers]]
[planes.modifiers.Noise]
mb = {area = {AABB = {x=270.0, z=50.0}}, loc = [-30.0, -110.0]}
noise = "RMPerlinSurflet"
seed = 0
scale = 0.2
global = false
easing = "SmoothStart" 
octaves = 1


# `Perlin`, `PerlinSurflet`, `OpenSimplex`, `Value`, `SuperSimplex`, `Worley`, 
# `Simplex`, `FBMPerlin`, `BMPerlin`, `BPerlin`, `RMPerlin`, `HMPerlin`, `FBMPerlinSurflet`, 
# `BMPerlinSurflet`, `BPerlinSurflet`, `RMPerlinSurflet`, `HMPerlinSurflet`, `FBMValue`, 
# `BMValue`, `BValue`, `RMValue`, `HMValue`, `FBMSS`, `BMSS`, `BSS`, `RMSS`, `HMSS`

