[[planes]]
name = "Water"
active = false
loc = [0.0, 60.0, 0.0]
subdivisions= [0,0]
dims = [1000.0, 1000.0]
color = {Color = [0.4, 0.92, 0.964, 1.0]}
modifiers = []

[[planes]]
name= "Test noise with easing"
active= true
loc= [0.0, 0.0, 0.0]
subdivisions= [50,50]
dims= [500.0, 500.0]
color = {Gradient = {low = [1.0, 0.0, 0.0, 1.0], high = [0.0, 1.0, 0.0, 1.0]}}

[[planes.modifiers]]
[planes.modifiers.Value]
mb = {area = {AABB = {x=1000.0, z=1000.0}}, loc = [0.0, 0.0]}
scaling = "None"
easing = "None"
val = {Value=5.0}

# [[planes.modifiers]]
# [planes.modifiers.Value]
# mb = {area = {Ellipse = {x=90.0, z=150.0}}, loc = [0.0, 0.0]}
# scaling = "None"
# easing = "None"
# val = {Diff=20.0}

[[planes.modifiers]]
[planes.modifiers.Value]
mb = {area = {Arc = {r=100.0, a=1.63}}, loc = [0.0, 0.0]}
scaling = "None"
easing = "None"
val = {Diff=20.0}


##### Waves

# [[planes.modifiers]]
# [planes.modifiers.Smoothing]
# mb = {area = {AABB = {x=10.0, z=10.0}}, loc = [85.0, -65.0]}
# method={DistanceToPoint=[100.0, 0.0, -65.0]}



# [[planes.modifiers]]
# [planes.modifiers.Wave]
# mb = {area = {AABB = {x=20.0, z=60.0}}, loc = [85.0, -50.0]}
# noise = {noise="Value", seed=1, scale= 0.4}
# scale_x = 3.0
# scale_z = 0.0

[[planes.modifiers]]
[planes.modifiers.Wave]
mb = {area = {AABB = {x=30.0, z=60.0}}, loc = [85.0, -65.0]}
noise = {noise="RMValue", seed=1, scale= 0.2}
scale_x = 10.0
scale_z = 0.0


# [[planes.modifiers]]
# [planes.modifiers.Wave]
# mb = {area = {AABB = {x=20.0, z=20.0}}, loc = [90.0, -65.0]}
# noise = {noise="Value", seed=123, scale= 0.4}
# scale_x = 1.0
# scale_z = 1.0


# [[planes.modifiers]]
# [planes.modifiers.Wave]
# mb = {area = {AABB = {x=100.0, z=20.0}}, loc = [0.0, 50.0]}
# noise = {noise="Value", seed=15, scale= 0.4}
# scale_x = 2.0
# scale_z = 4.0

# [[planes.modifiers]]
# [planes.modifiers.Wave]
# mb = {area = {AABB = {x=20.0, z=100.0}}, loc = [-53.0, 0.0]}
# noise = {noise="Value", seed=15125, scale= 0.4}
# scale_x = 4.0
# scale_z = 2.0

# `Perlin`, `PerlinSurflet`, `OpenSimplex`, `Value`, `SuperSimplex`, `Worley`, `Simplex`, `FBMPerlin`, 
# `BMPerlin`, `BPerlin`, `RMPerlin`, `HMPerlin`, `FBMPerlinSurflet`, `BMPerlinSurflet`, `BPerlinSurflet`,
#  `RMPerlinSurflet`, `HMPerlinSurflet`, `FBMValue`, `BMValue`, `BValue`, `RMValue`, `HMValue`, 
#  `FBMSS`, `BMSS`, `BSS`, `RMSS`, `HMSS`

